export const queueData = [
  {
    id: 1,
    rowClass: "row-red",
    nome: "Maria da Silva, 68",
    contexto: "Pressão alta, diabetes",
    sintomas: "Dor forte no peito irradiando para o braço, suor excessivo.",
    envio: "10:15",
    espera: "5 min",
    esperaCritica: true,
    risco: "1. Emergência",
    riscoCor: "red",
    acao: "Acionar Ambulância",
    acaoTipo: "ambulance",
    acaoIcone: "fa-truck-medical"
  },
  {
    id: 2,
    rowClass: "row-orange",
    nome: "João Souza, 45",
    contexto: "Sem comorbidades",
    sintomas: "Falta de ar intensa e febre alta desde ontem.",
    envio: "10:05",
    espera: "15 min",
    esperaCritica: false,
    risco: "2. Muito Urgente",
    riscoCor: "orange",
    acao: "Autorizar Ida à UPA",
    acaoTipo: "primary",
    acaoIcone: "fa-check"
  },
  {
    id: 3,
    rowClass: "row-yellow",
    nome: "Ana Clara, 22",
    contexto: "Sem comorbidades",
    sintomas: "Dor contínua na barriga com vômito e dificuldade de ficar em pé.",
    envio: "09:50",
    espera: "30 min",
    esperaCritica: false,
    risco: "3. Urgente",
    riscoCor: "yellow",
    acao: "Autorizar Ida à UPA",
    acaoTipo: "primary",
    acaoIcone: "fa-check"
  },
  {
    id: 4,
    rowClass: "row-green",
    nome: "Carlos Roberto, 35",
    contexto: "Asma",
    sintomas: "Entorse no tornozelo durante futebol, dor para apoiar.",
    envio: "09:20",
    espera: "1h 00m",
    esperaCritica: false,
    risco: "4. Pouco Urgente",
    riscoCor: "green",
    acao: "Orientar Remotamente",
    acaoTipo: "outline",
    acaoIcone: "fa-video"
  },
  {
    id: 5,
    rowClass: "row-blue",
    nome: "Lucas Martins, 19",
    contexto: "Sem comorbidades",
    sintomas: "Tosse e coriza há três dias.",
    envio: "08:30",
    espera: "1h 50m",
    esperaCritica: false,
    risco: "5. Não Urgente",
    riscoCor: "blue",
    acao: "Agendar UBS",
    acaoTipo: "outline",
    acaoIcone: "fa-calendar-check"
  }
];
